### ISSUE TITLE
DrawWindow's Draw() method causing screen update problems

### ISSUE THREAD

**Issue by ssDko** [sqrMin1/MonoGame.Forms#8]
EDIT: Btw using the DX version, if that matters.
Having a small problem with MonoGame.Forms.   For some reason if my class that derives from DrawWindow, calls base.Draw(), then any other control will not automatically update for changes.

I can force a update if I move the window, so it might be blocking invalidation some how? 

I've even tested it in other projects and different parts of the same project and get the same result. 

Bellow is a picture showing what my programs window looks like when I click the tab that has the DrawWindow. 

![error](https://user-images.githubusercontent.com/10103014/43029860-23c1dda0-8c58-11e8-860e-be116e6a0f83.png)

**Comment by sqrMin1** [comment]
> For some reason if my class that derives from DrawWindow, calls base.Draw(), **then any other control will not automatically update for changes**.

Do you mean native windows forms controls so that the UI got blocked?

Then you have two options:

- turning off [AutomaticInvalidation](https://github.com/sqrMin1/MonoGame.Forms/wiki/5EE93A47) and update your DrawWindow manually by calling **Invalidate()** after your actions (E.g. 1. Place Tile 2. Invalidate())
- Swapping your DrawWindow with an UpdateWindow, which shouldn't block UI.

**Comment by ssDko** [comment]
Swaping to a UpdateWindow worked perfectly. Man I'm an idiot. Thank you.
