### ISSUE TITLE
is there a equivalent of Load, Unload, and Update for monogame forms? 

### ISSUE THREAD

**Issue by Shadowblitz16** [sqrMin1/MonoGame.Forms#9]
is there a equivalent of Load, Unload, and Update for monogame forms? 
I would like to contain my code inside these forms kinda like states.

Kinda like this..

    using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;

	namespace TileTestForms
	{
		public class Window : MonoGame.Forms.Controls.DrawWindow
		{
			protected override void Initialize()
			{
				base.Initialize();
			}

			protected override void LoadContent()
			{

			}

			protected override void UnLoadContent()
			{

			}

			protected override void Update()
			{

			}

			protected override void Draw()
			{
				base.Draw();
			}
		}
	}

if not would that be possible to add?
it would make this even easier to build monogame editors

**Comment by sqrMin1** [comment]
```c#
protected override void Update(GameTime gameTime)
{
    base.Update(gameTime);
}
```

This override is already available when you inherit from an [UpdateWindow](https://github.com/sqrMin1/MonoGame.Forms/wiki/30D3E59D). 

It is not available in a DrawWindow, simply because it has no update cycle (or game loop).

The overrides of LoadContent and UnloadContent are currently not available in MonoGame.Forms, but yes, I can implement this in the next version.

Thank you for your suggestion.

**Comment by Shadowblitz16** [comment]
so wait is UpdateWindow a monogame.form control?
does it have a Draw() and Initalize() event too?
if so I might inherit from that instead of a drawWindow

**Comment by sqrMin1** [comment]
Yes.
